version: '3.8'

services:
  db:
    image: hakdyr24/logisticaglobal:mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: incidentesdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: hakdyr24/logisticaglobal:backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: ["bash", "-c", "/wait-for-it.sh db:3306 -t 60 -- npm start"]

  frontend:
    image: hakdyr24/logisticaglobal:frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  cypress:
    image: cypress/included:13.7.3
    depends_on:
      - frontend
    working_dir: /e2e
    volumes:
      - ./:/e2e
    environment:
      - CYPRESS_baseUrl=http://frontend:5173
    command: >
      sh -c "
        echo 'Esperando a que frontend esté listo...';
        npx wait-on http://frontend:5173 &&
        npx cypress run --config-file cypress.config.js
      "

volumes:
  db_data:
