FROM node:18

# Esperar a MySQL por 10 segundos
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

WORKDIR /app

COPY package*.json ./
RUN npm install && npm install cors

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
